name: DiamondAVO
version: 6
main: org.avo.diamondAVO.DiamondAVO
api-version: 1.20
commands:
  avodiamond:
    description: Manage diamond score
    usage: /<command> sco <add|set|remove> <amount>
  ch:
    description: เปิดกล่องเก็บของเต็ม
    usage: /<command>